from flask import Flask, render_template, request, session, redirect, url_for, jsonify
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3, os, json, re
from functools import wraps
from event_service import get_events, get_event_detail
from avatar_utils import (
    get_avatar_url,
    generate_random_seed,
    AVATAR_STYLES,
    POPULAR_STYLES,
)

app = Flask(__name__)
app.secret_key = "buzzz-secret-key-2026"

DB_PATH = os.path.join("data", "buzzz.db")
os.makedirs("data", exist_ok=True)

# ── DB ─────────────────────────────────────────────
def get_db():
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    return c

def init_db():
    with get_db() as db:
        # Create table if it doesn't exist at all
        db.executescript("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                avatar_icon TEXT DEFAULT 'adventurer',
                avatar_color TEXT DEFAULT '',
                avatar_bg TEXT DEFAULT '',
                bio TEXT DEFAULT '',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
        """)
        # Migrate: add any missing columns to an existing table
        existing = {row[1] for row in db.execute("PRAGMA table_info(users)").fetchall()}
        migrations = [
            ("avatar_icon",  "TEXT DEFAULT 'adventurer'"),
            ("avatar_color", "TEXT DEFAULT ''"),
            ("avatar_bg",    "TEXT DEFAULT ''"),
            ("bio",          "TEXT DEFAULT ''"),
        ]
        for col, definition in migrations:
            if col not in existing:
                db.execute(f"ALTER TABLE users ADD COLUMN {col} {definition}")
                print(f"[DB] Added missing column: {col}")
init_db()

# ── AUTH HELPERS ──────────────────────────────────
def login_required(f):
    @wraps(f)
    def w(*a, **kw):
        if "user_id" not in session:
            return redirect(url_for("welcome"))
        return f(*a, **kw)
    return w

# ── ROUTES ────────────────────────────────────────
@app.route("/")
def welcome():
    if "user_id" in session:
        return redirect(url_for("events_page"))
    return render_template("welcome.html")

@app.route("/signup")
def signup():
    return render_template("auth.html", mode="signup")

@app.route("/login")
def login():
    return render_template("auth.html", mode="login")

# ── SIGNUP API ────────────────────────────────────
@app.route("/api/signup", methods=["POST"])
def api_signup():
    d = request.get_json()
    if not d:
        return jsonify({"error": "Invalid request."}), 400

    name     = d.get("name", "").strip()
    username = d.get("username", "").strip().lower()
    email    = d.get("email", "").strip().lower()
    password = d.get("password", "")

    # Avatar fields — frontend sends avatar_seed + avatar_style
    # (generated by the DiceBear picker in auth.html)
    avatar_seed  = d.get("avatar_seed", "").strip()
    avatar_style = d.get("avatar_style", "adventurer").strip()

    # Fallbacks if frontend didn't send them
    if not avatar_seed:
        avatar_seed = generate_random_seed()
    if avatar_style not in AVATAR_STYLES:
        avatar_style = "adventurer"

    # Build the full URL once, store it
    avatar_url = get_avatar_url(avatar_seed, avatar_style)

    # ── Validation ──
    if not all([name, username, email, password]):
        return jsonify({"error": "All fields required."}), 400
    if len(username) < 3:
        return jsonify({"error": "Username must be at least 3 characters."}), 400
    if not re.match(r"^[a-z0-9_]+$", username):
        return jsonify({"error": "Username may only contain letters, numbers and underscores."}), 400
    if not re.match(r"^[^@]+@[^@]+\.[^@]+$", email):
        return jsonify({"error": "Please enter a valid email address."}), 400
    if len(password) < 6:
        return jsonify({"error": "Password must be at least 6 characters."}), 400

    try:
        with get_db() as db:
            db.execute("""
                INSERT INTO users
                  (name, username, email, password_hash,
                   avatar_icon, avatar_color, avatar_bg)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                name,
                username,
                email,
                generate_password_hash(password),
                avatar_style,   # avatar_icon  → style name e.g. "adventurer"
                avatar_seed,    # avatar_color → seed string
                avatar_url,     # avatar_bg    → full DiceBear URL
            ))

            u = db.execute(
                "SELECT * FROM users WHERE username = ?", (username,)
            ).fetchone()

            session.update({
                "user_id" : u["id"],
                "username": u["username"],
                "name"    : u["name"],
            })

        return jsonify({"ok": True, "redirect": "/onboarding"})

    except sqlite3.IntegrityError:
        return jsonify({"error": "Username or email already exists."}), 400

# ── LOGIN API ─────────────────────────────────────
@app.route("/api/login", methods=["POST"])
def api_login():
    d = request.get_json()
    if not d:
        return jsonify({"error": "Invalid request."}), 400

    username = d.get("username", "").strip().lower()
    password = d.get("password", "")

    if not username or not password:
        return jsonify({"error": "Username and password are required."}), 400

    with get_db() as db:
        u = db.execute(
            "SELECT * FROM users WHERE username = ?", (username,)
        ).fetchone()

    if not u or not check_password_hash(u["password_hash"], password):
        return jsonify({"error": "Invalid username or password."}), 401

    session.update({
        "user_id" : u["id"],
        "username": u["username"],
        "name"    : u["name"],
    })

    return jsonify({"ok": True, "redirect": "/events"})

# ── AVATAR HELPERS ────────────────────────────────
def get_user_avatar(user):
    """
    Return a DiceBear URL for a user.
    Prefers the stored full URL (avatar_bg); falls back to
    rebuilding it from style (avatar_icon) + seed (avatar_color).
    """
    if user.get("avatar_bg"):
        return user["avatar_bg"]
    seed  = user.get("avatar_color") or user.get("username", "default")
    style = user.get("avatar_icon", "adventurer")
    return get_avatar_url(seed, style)

app.jinja_env.globals["get_user_avatar"] = get_user_avatar

@app.route("/api/avatar/styles")
def get_avatar_styles():
    return jsonify({"styles": AVATAR_STYLES, "popular": POPULAR_STYLES})

# ── EVENTS ────────────────────────────────────────
@app.route("/events")
@login_required
def events_page():
    prefs  = {}
    me     = {}
    events, source = get_events()
    return render_template("events.html", events=events, prefs=prefs,
                           source=source, me=me)

# ── LOGOUT ────────────────────────────────────────
@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("welcome"))

# ── RUN ───────────────────────────────────────────
if __name__ == "__main__":
    print("\n buzzz. is live")
    print(" http://localhost:5000\n")
    app.run(debug=True, port=5000)